<!-- application/views/scripts/guestbook/index.phtml -->
Guestbook Entries:
<br />
<ul id="comments">
<?php foreach ($this->entries as $entry): ?>
    <li class="comment-main">
    <div class="comment-header">
    <?php echo $this->escape($entry->email) ?>
    </div>
    <p class="comment"><?php echo $this->escape($entry->comment) ?></p>
    </li>
    <?php endforeach ?>
</ul>
<?php echo $this->form ?>
