<?php $paginationControl = $this->paginationControl(
    $this->paginator,
    'Sliding',
    'index_pagination.phtml'
);?>
<?php echo $paginationControl ?>
<div class="paged-data">
<?php if (count($this->paginator) > 0): ?>
<ul id="comments">
<?php foreach ($this->paginator as $entry): ?>
    <li class="comment-main">
        <div class="comment-header">
            <span><?php echo $this->escape($entry['entry']->created) ?></span>
            <span><strong><?php echo $this->escape($entry['entry']->email) ?></strong></span>
            <span><?php echo $this->escape($entry['entry']->username) ?></span>
            <span><?php echo $this->escape($entry['entry']->url) ?></span>
            <span class="number">№<?php echo $this->escape($entry['entry']->gid) ?></span>
        </div>
        <?php if ('' !== $entry['image']->filename): ?>
            <a href="/images/<?php echo $this->escape($entry['image']->filename) ?>"
                rel="lightbox">
            <img class="image"
                src="/images/thumbs/<?php echo $this->escape($entry['image']->filename) ?>"
                alt="<?php echo $this->escape($entry['image']->filename) ?>"
                width="<?php echo $this->escape($entry['image']->resizedwidth) ?>"
                height="<?php echo $this->escape($entry['image']->resizedheight) ?>"
            /></a>
        <?php endif;?>
        <div class="comment-text"><?php echo $entry['entry']->comment ?></div>
    </li>
    <?php endforeach ?>
</ul>
<?php else :?>
<p>No items found</p>
<?php endif;?>
</div>
<?php echo $paginationControl ?>