<?php $paginationControl = $this->paginationControl(
    $this->paginator,
    'Sliding',
    'index_pagination.phtml'
);?>
<?php echo $paginationControl ?>
<div class="paged-data">
<?php if (count($this->paginator) > 0): ?>
<ul id="comments">
<?php foreach ($this->paginator as $entry): ?>
    <li class="comment-main">
        <div class="comment-header">
            <span><?php echo $this->escape($entry['entry']->created) ?></span>
            <span><strong><?php echo $this->escape($entry['entry']->email) ?></strong></span>
            <span><?php echo $this->escape($entry['entry']->username) ?></span>
            <span><?php echo $this->escape($entry['entry']->url) ?></span>
            <span class="number">№<?php echo $this->escape($entry['entry']->gid) ?></span>
        </div>
        <?php if ('' !== $entry['image']->filename): ?>
            <a href="/images/<?php echo $this->escape($entry['image']->filename) ?>"
                rel="lightbox">
            <img class="image"
                src="/images/thumbs/<?php echo $this->escape($entry['image']->filename) ?>"
                alt="<?php echo $this->escape($entry['image']->filename) ?>"
                width="<?php echo $this->escape($entry['image']->resizedwidth) ?>"
                height="<?php echo $this->escape($entry['image']->resizedheight) ?>"
            /></a>
        <?php endif;?>
        <div class="comment-text"><?php echo $entry['entry']->comment ?></div>
    </li>
    <?php endforeach ?>
</ul>
<?php else :?>
<p>No items found</p>
<?php endif;?>
</div>
<script type="text/javascript">
    function path()
    {
        var args = arguments,
            result = [];

        for(var i = 0; i < args.length; i++)
            result.push(args[i].replace('@', '/syntaxhighlight/scripts/'));

        return result
    };

    SyntaxHighlighter.autoloader.apply(null, path(
      'applescript            @shBrushAppleScript.js',
      'actionscript3 as3      @shBrushAS3.js',
      'bash shell             @shBrushBash.js',
      'coldfusion cf          @shBrushColdFusion.js',
      'cpp c                  @shBrushCpp.js',
      'c# c-sharp csharp      @shBrushCSharp.js',
      'css                    @shBrushCss.js',
      'delphi pascal          @shBrushDelphi.js',
      'diff patch pas         @shBrushDiff.js',
      'erl erlang             @shBrushErlang.js',
      'groovy                 @shBrushGroovy.js',
      'java                   @shBrushJava.js',
      'jfx javafx             @shBrushJavaFX.js',
      'js jscript javascript  @shBrushJScript.js',
      'perl pl                @shBrushPerl.js',
      'php                    @shBrushPhp.js',
      'text plain             @shBrushPlain.js',
      'py python              @shBrushPython.js',
      'ruby rails ror rb      @shBrushRuby.js',
      'sass scss              @shBrushSass.js',
      'scala                  @shBrushScala.js',
      'sql                    @shBrushSql.js',
      'vb vbnet               @shBrushVb.js',
      'xml xhtml xslt html    @shBrushXml.js'
    ));
    SyntaxHighlighter.config.stripBrs = true;
    SyntaxHighlighter.all();
    Shadowbox.setup();
</script>
<?php echo $paginationControl ?>