<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headTitle() ?>
    <link rel="stylesheet" href="<?php echo $this->baseUrl()?>/css/picbox/picbox.css" type="text/css" media="screen" />
</head>
<body>
    <header id="header">
        <h1><a href="/"><?php echo $this->title ?></a></h1>
    </header>
    <div id="wrapper">
        <section id="content">
            <?php echo $this->layout()->content ?>
        </section> <!-- content -->
    </div> <!-- wrapper -->
    <footer id="footer">
        <p>&copy; login.was.here <?php echo date('Y') ?></p>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl()?>/js/picbox/picbox.js" type="text/javascript"></script>
</body>
</html>