<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink()->appendStylesheet('/shadowbox/shadowbox.css') ?>
    <?php echo $this->headTitle() ?>
</head>
<body>
    <header id="header">
        <h1><a href="/"><?php echo $this->title ?></a></h1>
    </header>
    <div id="wrapper">
        <section id="content">
            <?php echo $this->layout()->content ?>
        </section> <!-- content -->
    </div> <!-- wrapper -->
    <footer id="footer">
        <p>&copy; <a href="http://loginwashere.pp.ua/">login.was.here</a> <?php echo date('Y') ?></p>
    </footer>
    <?php echo $this->jQuery(); ?>
    <?php echo $this->headScript()
                ->prependFile($this->baseUrl() . '/js/modernizr-1.7.min.js')
                ->prependFile('http://ajax.aspnetcdn.com/ajax/jquery.validate/1.8.1/jquery.validate.min.js')
                ->appendFile($this->baseUrl() . '/shadowbox/shadowbox.js')
                ->appendFile($this->baseUrl() . '/js/main.js')
    ?>
    <script type="text/javascript">
    Shadowbox.init();
    </script>
</body>
</html>